// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/user","layout":false,"id":"1"},"2":{"path":"/user/login","name":"login","parentId":"1","id":"2"},"3":{"path":"/user/register","name":"register","parentId":"1","id":"3"},"4":{"path":"/","redirect":"/dashboard","id":"4"},"5":{"path":"/dashboard","name":"dashboard","icon":"Dashboard","id":"5"},"6":{"path":"/admin","name":"admin","icon":"User","id":"6"},"7":{"path":"/admin/user","name":"user","parentId":"6","id":"7"},"8":{"path":"/admin/role","name":"role","parentId":"6","id":"8"},"9":{"path":"/admin/permission","name":"permission","parentId":"6","id":"9"},"10":{"path":"/statistics","name":"statistics","icon":"LineChart","id":"10"},"11":{"path":"/profile","name":"profile","icon":"User","id":"11"},"12":{"path":"*","id":"12"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__User__Login" */'@/pages/User/Login.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__User__Register" */'@/pages/User/Register.tsx')),
'4': React.lazy(() => import('./EmptyRoute')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Dashboard" */'@/pages/Dashboard.tsx')),
'6': React.lazy(() => import('./EmptyRoute')),
'7': React.lazy(() => import(/* webpackChunkName: "p__Admin__User" */'@/pages/Admin/User.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__Admin__Role" */'@/pages/Admin/Role.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__Admin__Permission" */'@/pages/Admin/Permission.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__Statistics" */'@/pages/Statistics.tsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__Profile" */'@/pages/Profile.tsx')),
'12': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
},
  };
}
